import { OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import 'jquery-ui-npm/jquery-ui.min.js';
import { DnLoadingBase } from '../../../../components/loading/dn-loading.base';
import { DnSelect2Item } from '../../../../components/select/select2/dn-select2-item';
import { DnHttpService } from '../../../../services/http.service';
import { DnNotificationService } from '../../../../services/notification.service';
import { DnAuthService } from '../../../auth/auth.service';
export declare class DnRoleGroupListComponent extends DnLoadingBase implements OnInit {
    private _http;
    private _nfs;
    private _fb;
    private _authService;
    roleGrubuListesi: any[];
    roleListesi: any[];
    roleGrubuFilteredList: any[];
    roleGrubuSelectedRow: number;
    roleGrupDialog: any;
    roleGrubuEditForm: FormGroup;
    roleAtamaLoading: boolean;
    dinazorRoles: any;
    auth: DnAuthService;
    private roleGrubuTerm;
    private roleGrubuSearchTerm;
    private roleGroupChangeEmitter;
    constructor(_http: DnHttpService<any>, _nfs: DnNotificationService, _fb: FormBuilder, _authService: DnAuthService);
    editRoleGrubu(item: any): void;
    isAuth(roles: any): boolean;
    ngOnInit(): void;
    onSelectRole(item: DnSelect2Item): void;
    removeRoleFromGroup(item: any): void;
    removeRoleGrubu(item: any): void;
    roleGrubuSearchKeypress(e: any): void;
    saveRoleGrubu(): void;
    saveRoleGrubuKeypress(e: any): void;
    searchRoleGrubu(): void;
    private editRoleGurubu(data);
    private getRoleGrubuEditDialogOptions();
    private loadRoleFromRoleGroup(id);
    private loadRoleGrubu();
    private setClickedRoleGrubuRow(i);
}
