import { ElementRef, EventEmitter, OnInit } from '@angular/core';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import { DnHttpService } from '../../services/http.service';
import { DnNotificationService } from '../../services/notification.service';
import { DnAuthService } from '../../views/auth/auth.service';
import { DnDatatableComponent } from '../datatable/dn-datatable.component';
import { DnCrudBase } from './dn-crud-base';
export declare class DnCrudComponent implements OnInit {
    el: ElementRef;
    private dnHttpService;
    private notificationService;
    private authService;
    editFormData: any;
    currentId: any;
    isEdit: boolean;
    crudData: DnCrudBase;
    datatableComponent: DnDatatableComponent;
    actionBeforeEditShowPanelEmitter: EventEmitter<string>;
    actionAfterEditShowPanelEmitter: EventEmitter<string>;
    actionBeforeDeleteEmitter: EventEmitter<string>;
    actionAfterDeleteEmitter: EventEmitter<string>;
    actionBeforeEditEmitter: EventEmitter<string>;
    actionAfterEditEmitter: EventEmitter<string>;
    actionBeforeSearchEmitter: EventEmitter<string>;
    actionAfterSearchEmitter: EventEmitter<string>;
    auth: DnAuthService;
    private isOpen;
    constructor(el: ElementRef, dnHttpService: DnHttpService<any>, notificationService: DnNotificationService, authService: DnAuthService);
    actionDelete(data: any): void;
    actionEdit(data: any): void;
    closeEditPanel(): void;
    ngOnInit(): void;
    onSubmit(data: any, type: string, isEdit: boolean): void;
    openEditPanel(): void;
    openNewDataPanel(): void;
    showPanel(): void;
    private deleteProcess(id);
    private editProcess(data);
    private getColumnTitle(column);
    private newDataProcess(data);
    private visibilityColumns(visible);
}
