declare const _default: {
    grid: string;
    widgets: string;
    localStorage: boolean;
    deleteSettingsKey: string;
    settingsKeyLabel: string;
    deletePositionKey: string;
    positionKeyLabel: string;
    sortable: boolean;
    buttonsHidden: boolean;
    toggleButton: boolean;
    toggleClass: string;
    toggleSpeed: number;
    onToggle: () => void;
    deleteButton: boolean;
    deleteMsg: string;
    deleteClass: string;
    deleteSpeed: number;
    onDelete: () => void;
    editButton: boolean;
    editPlaceholder: string;
    editClass: string;
    editSpeed: number;
    onEdit: () => void;
    colorButton: boolean;
    fullscreenButton: boolean;
    fullscreenClass: string;
    fullscreenDiff: number;
    onFullscreen: () => void;
    customButton: boolean;
    customClass: string;
    customStart: () => void;
    customEnd: () => void;
    buttonOrder: string;
    opacity: number;
    dragHandle: string;
    placeholderClass: string;
    indicator: boolean;
    indicatorTime: number;
    ajax: boolean;
    timestampPlaceholder: string;
    timestampFormat: string;
    refreshButton: boolean;
    refreshButtonClass: string;
    labelError: string;
    labelUpdated: string;
    labelRefresh: string;
    labelDelete: string;
    afterLoad: () => void;
    rtl: boolean;
    onChange: () => void;
    onSave: () => void;
    ajaxnav: boolean;
};
export default _default;
