import { ElementRef, EventEmitter, OnInit } from '@angular/core';
import { ControlValueAccessor, FormGroup } from '@angular/forms';
import { Observable } from 'rxjs/Rx';
import { DnSelect2Item } from '../dn-select2-item';
import { DnSelect2Component } from '../dn-select2.component';
import { DnSelect2Service } from '../dn-select2.service';
export declare class DnSelect2SmartContainerComponent implements ControlValueAccessor, OnInit {
    private formControlName;
    private disabled;
    private _el;
    onSelect: EventEmitter<DnSelect2Item>;
    onRemove: EventEmitter<DnSelect2Item>;
    form: FormGroup;
    minimumInputLength: number;
    placeholder: string;
    serviceUrl: string;
    label: string;
    name: string;
    multiple: boolean;
    message: any[];
    labelRow: number;
    inputRow: number;
    col: number;
    icon: string;
    inputCss: string;
    number: boolean;
    referenceMode: 'entity' | 'id';
    hasLabel: boolean;
    isDisabled: boolean;
    termLabel: any;
    termSelect: DnSelect2Component<any>;
    private innerValue;
    private formErrors;
    private validationMessages;
    private onTouchedCallback;
    private onChangeCallback;
    private control;
    displaySelect: (_: DnSelect2Item) => string;
    selectedText: (_: DnSelect2Item) => string;
    constructor(formControlName: any, disabled: any, _el: ElementRef);
    value: any;
    getSelect2(): DnSelect2Component<any>;
    getService(): DnSelect2Service;
    initializeValidationData(): void;
    ngOnInit(): void;
    onBlur(): void;
    onItemSelected(item: DnSelect2Item): void;
    onRemoveEvent(item: DnSelect2Item): void;
    onSelectEvent(item: DnSelect2Item): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    subscribeToResults(observable: Observable<string>): void;
    writeValue(value: any): void;
    private css();
    private subscribeToChangesAndLoadDataFromObservable();
}
