export const dinazorRoles: any = {
    UserView : 1,
    UserSave : 2,
    UserDelete : 3,
    UserUpdate : 4,
    UserGroupView : 5,
    UserGroupSave : 6,
    UserGroupDelete : 7,
    UserGroupUpdate : 8,
    RoleGroupView : 9,
    RoleGroupSave : 10,
    RoleGroupDelete : 11,
    RoleGroupUpdate : 12,
    TenantView : 13,
    TenantSave : 14,
    TenantDelete : 15,
    TenantUpdate : 16,
    RiskBilgiView : 100,
    RiskBilgiSave : 101,
    RiskBilgiDelete : 102,
    RiskBilgiUpdate : 103
};
